language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - android-16
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-16

before_install: 
  - echo yes | android update sdk --all --filter build-tools-28.0.3 --no-ui --force
  - touch local.properties
  - chmod +x gradlew
  - echo no | android create avd --force -n test -t android-16 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &
 
script:
 - ./gradlew clean build connectedCheck
