language: android
jdk: oraclejdk8
sudo: false

android:

  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    
before_script:
  - echo yes | android update sdk --all --filter build-tools-28.0.3 --no-ui --force
  - touch local.properties
  - chmod +x gradlew
 
script:
 - ./gradlew clean build
